# Generated by Django 5.1.3 on 2024-11-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_host_event_user'),
        ('wishnests', '0003_wishnest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishnest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishnests', to='events.event'),
        ),
    ]
