# Generated by Django 5.1.3 on 2024-11-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishnests', '0004_alter_wishnest_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishnest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='wishnest',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
