# Generated by Django 5.1.3 on 2024-11-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishnests', '0005_remove_wishnest_updated_at_wishnest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishnest',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
