# Generated by Django 5.1.3 on 2024-11-20 00:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_gift_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
