# Generated by Django 5.1.3 on 2024-11-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_alter_gift_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
