# Generated by Django 5.1.3 on 2024-11-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_gift_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='registered_by_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
