# Generated by Django 5.1.3 on 2024-11-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_gift_registered_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='registered_by_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
    ]
