# Generated by Django 5.1.3 on 2024-11-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0007_alter_gift_registered_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='registered_by_name',
            field=models.CharField(max_length=50),
        ),
    ]
