# Generated by Django 5.1.3 on 2024-11-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0008_alter_gift_registered_by_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='registered_by_name',
        ),
        migrations.AddField(
            model_name='gift',
            name='registered_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
