# Generated by Django 5.1.3 on 2024-11-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='user',
        ),
    ]
