# Generated by Django 5.1.3 on 2024-12-08 20:25

import WishNestApp.events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(validators=[WishNestApp.events.validators.validate_future_date]),
        ),
    ]
