# Generated by Django 5.1.3 on 2024-11-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hug',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
