# Generated by Django 5.1.3 on 2024-11-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sharelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
