# Generated by Django 5.1.3 on 2024-11-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_sharelink_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hug',
            name='name',
        ),
        migrations.AddField(
            model_name='hug',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
